### ISSUE TITLE
[Swift] Delegate (Pattern)

### ISSUE THREAD

**Issue by Lia316** [zzisun/SwiftStudy#10]
## 면접 질문 리스트
- UITableViewController나 UICollectionViewController에 대한 Datasource/Delegate 지정할 수 있고 동작 원리를 설명할 수 있다.
- Delegate란 무언인가 설명하고, retain 되는지 안되는지 그 이유를 함께 설명하시오.
- Delegate 패턴을 활용하는 경우를 예를 들어 설명하시오.
- Delegates와 Notification 방식의 차이점에 대해 설명하시오.
- NSURLConnection 에서 사용하는 Delegate 메서드들에 대해 설명하시오.

**Comment by torch-ray** [comment]
요건 직접 닫아주세요 ~ 다 끝나셨다고 생각드시면 ㅎㅎ

**Comment by Lia316** [comment]
넹~ 완료!
