### ISSUE TITLE
[Swift] Open Source

### ISSUE THREAD

**Issue by torch-ray** [zzisun/SwiftStudy#20]
- 같이 contribute할 Open Source를 골라주세요.
- 이유와 함께 목요일까지 슬랙에 남겨주세요.

**Comment by Lia316** [comment]
1. Alamofire 
  - 분석하면서 네트워크의 기반도 다지게 되지 않을까 기대함
  - 네트워크 연결에 대한 이해가 높아지면 앱 성능에도 영향을 미칠테니 좋을 거라 판단함
2. SwiftLint
  - 클린 코드를 배우게 되지 않을까 생각함
3. Realm
  - Alamofire 와 비슷한 이유로, Persistence 에 대한 이해가 높아지지 않을까 기대함
  - 이 또한 앱 성능에 영향을 미칠테니 좋을 거라 판단함
4. Swift
  - 도 오픈소스다,,,
  - 마찬가지로 기본적인 스위프트에 대한 이해가 높아질 것이라 기대함

결국 분석하는 과정에서 배우는 게 클 것 같다고 생각해서 그런가
공부하고 싶은 걸 적은 느낌이네요 😅

**Comment by zzisun** [comment]
1번째 오픈소스는 Alamofire입니다🎉
